### ISSUE TITLE
Sanitize input before sending it to go parser (for arithmetic parser)

### ISSUE THREAD

**Issue by gekkowrld** [NuruProgramming/Nuru#79]
### Describe the bug

When I tried to do arithmetic operations with non int values, it panics and exits with `SIGSEGV` error.
This is the expected behaviour when using go directly, can this behaviour be mitigated.
It works with alphabets ([a-zA-Z]) and some punctuations but panics on encountering others and UTF-8 characters.

### Expected Behavior

>>> 1+.
	Mstari 1: Tumeshindwa kuparse .
>>>

### Current Behavior

>>> 1+.
	Mstari 1: Tumeshindwa kuparse .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f8fc7]

goroutine 1 [running]:
github.com/AvicennaJr/Nuru/evaluator.evalInfixExpression({0xc0003ee2d4, 0x1}, {0xfdb2a0, 0xc0003ee2e8}, {0x0, 0x0}, 0x1)
	/tmp/nuru/evaluator/infix.go:68 +0x867
github.com/AvicennaJr/Nuru/evaluator.Eval({0xfdb548?, 0xc00058e120}, 0xc00041b000)
	/tmp/nuru/evaluator/evaluator.go:51 +0x157a
github.com/AvicennaJr/Nuru/evaluator.Eval({0xfdb480?, 0xc000404080}, 0xc00041b000)
	/tmp/nuru/evaluator/evaluator.go:24 +0x865
github.com/AvicennaJr/Nuru/evaluator.evalProgram(0x32?, 0xc00041b000)
	/tmp/nuru/evaluator/evaluator.go:212 +0x85
github.com/AvicennaJr/Nuru/evaluator.Eval({0xfdb040?, 0xc00043a030}, 0xc00041b000)
	/tmp/nuru/evaluator/evaluator.go:21 +0x209
github.com/AvicennaJr/Nuru/repl.(*dummy).executor(0xc000056530, {0xc0003ee248, 0x3})
	/tmp/nuru/repl/repl.go:113 +0x217
github.com/AvicennaJr/GoPrompt.(*Prompt).Run(0xc00017a5a0)
	/home/gekkowrld/go/pkg/mod/github.com/!avicenna!jr/!go!prompt@v0.0.0-20230411215003-be2316d88e2d/prompt.go:84 +0x73f
github.com/AvicennaJr/Nuru/repl.Start()
	/tmp/nuru/repl/repl.go:90 +0x15f
main.main()
	/tmp/nuru/main.go:40 +0x752

### Reproduction Steps

Type nuru into the terminal or open a file for editing.
Write a simple line like `1+.` or any puntuation marks except `[` and [a-zA-Z].
If on the terminal, press ENTER.
If in file, execute the file with `nuru filename.nr`
The panic happens and exits (in both file and terminal)
Repeat with another puntuation or UTF-8 or any other characters of your choice except ones from the list:

- a-z
- A-Z
- [SPACES] (except NULL or NOTHING)
- 0-9
- [, -

All the other characters can reproduce the error(s)

Adding one more operation, `-` is removed from the 'safe' panic list.

### Possible Solution

Catch the errors and produce custom errors as done with ASCII alphabet as now.

### Nuru version

v0.5.1 (compiled from source)

### Environment details (OS name and version, etc.)

GO VERSION: go version go1.22.0 linux/amd64
Kernel: 6.7.5-arch1-1 x86_64
Shell: Bash
OS: Arch Linux x86_64

**Comment by gekkowrld** [comment]
I have traced the error to how the dot {and other punctuations} is handled.
In the function [`parseExpression`](https://github.com/NuruProgramming/Nuru/blob/main/parser/parser.go#L231), in the line where the infix and prefix are handled, the value returned is `nil` if it doesn't recognize, this I guess makes the other functions thereafter try to handle a `nil` value. This panics can be as explained by [digital ocean](https://www.digitalocean.com/community/tutorials/handling-panics-in-go) and [uber](https://www.uber.com/en-KE/blog/nilaway-practical-nil-panic-detection-for-go/).

(hypothesis)
Due to the `nil` derefence in an array, it causes the error for example:

1+.
two values are allocated space for 1 and `nil`, since the later actions will try and get the value of `nil` it fails and panics when trying to handle the error.
This occurs since `nil` values have no memory allocated for them, and when trying to get the values, the values are to be gotten from "memory" which doesn't exist.

**Comment by gekkowrld** [comment]
@AvicennaJr are you working on this?
